makelib/common.mk
makelib/helm.mk

This update will allow the build scripts in the crossplane project to export the location of the helm tool in the .cache directory.
Signed-off-by: HashedDan <daniel.mangum@slalom.com>

build: updated build.vars to include helm tool location

---

makelib/golang.mk

https://github.com/golangci/golangci-lint is much more thorough and highly configurable. It should catch many more issues than go lint - which means we should be careful about merging this commit lest it break builds unexpectedly.

Lint Go code with golangci-lint rather than go lint

---

makelib/golang.mk

We're assuming that it's always run in correct order in a CI system to avoid duplicate test runs on our build pipeline.

Remove go.test.unit as a dependency for codecov

---

makelib/golang.mk
run

This PR does two things:
Causes `golint-ci` to output checkstyle XML to a file (as opposed to human readable output to the terminal) when the environment variable `RUNNING_IN_CI` is true. I considered automatically attempting to detect a TTY from within `make`, as well as testing for the presence of the `JENKINS_URL` environment variable. I settled on being as explicit as possible - i.e. depending on the CI runner (in our case Jenkins) to set `RUNNING_IN_CI=true`
Configures `make build` to run `make go.lint` (i.e. `golangci-lint`) instead of running `make go.fmt` and `make go.vet`. `golangci-lint` runs many linters, including `gofmt` and `go vet`, and runs fast. This change means builds will not pass if the linter fails, and means we're not invoking the same linters multiple times. Note …

Gate Go builds on the linter

---

makelib/golang.mk

```
$ make distclean
09:39:10 [ .. ] cleaning images for build-3af134bd
09:39:10 [ OK ] cleaning images for build-3af134bd
$ make lint
09:39:12 [ .. ] installing helm darwin-amd64
09:39:19 [ OK ] installing helm darwin-amd64
Creating /Users/negz/control/go/src/github.com/crossplaneio/crossplane/.work/helm/repository                                                                               
Creating /Users/negz/control/go/src/github.com/crossplaneio/crossplane/.work/helm/repository/cache                                                                         
Creating /Users/negz/control/go/src/github.com/crossplaneio/crossplane/.work/helm/repository/local                                                                         
Creating …
```

Install a concrete version of golangci-lint

---

cross/Dockerfile
makelib/golang.mk

I've built Crossplane by running `GO_SUPPORTED_VERSIONS=1.12 make build` with Go 1.12.1 and confirmed it starts and runs on my minikube.
Signed-off-by: Nic Cope <negz@rk0n.org>

Build using Go 1.12

---

cross/Dockerfile
makelib/golang.mk
makelib/kubebuilder.mk

- New targets:
- go.test.unit.nocov
- go.fmt.simplify
- kubebuilder.bin
Signed-off-by: Sam Leavens <rbwsam@gmail.com>

Updating kubebuilder to 1.0.8, new go targets

---

makelib/golang.mk

I just ran `make distclean && make test` on Crossplane and the tests failed due to the vendor directory not existing.

Initialise Go dependencies before running tests

---

makelib/golang.mk

We have so many tests now in Crossplane that it's difficult to find which ones have failed amongst the wall of output when running `make test`. I don't think we're getting a lot of value from seeing every passing test name printed out; I hand hacked this to try it out and identifying which tests failed is a lot easier (and just as detailed) without `-v`.

Do not run Go tests in verbose mode

---

makelib/golang.mk

It turns out we need verbose output in order to parse the output for JUnit.

Run verbose Go tests when running in CI

---

makelib/k8s_tools.mk

cross Dockerfile is updated to have `kubectl`, `kind`, and `helm` backed to to it. These tools are used to do integration testing in Crossplane

adding tools for integration tests

---

makelib/golang.mk

Align golangci-lint with the latest released version so users working
with opinionated IDEs aren't suprised by linting errors that haven't
been surfaced through the build system.
Signed-off-by: Marques Johansson <marques@upbound.io>

update golangci-lint to 1.17.1

---

makelib/common.mk

`HOSTOS` and `HOSTARCH` values are hardcoded in `minikube.sh` and `integration_tests.sh`. Adding these to `build.vars` target, so it could be read from there, rather than being hardcoded.
Signed-off-by: soorena776 <javad@upbound.io>

adding HOSTOS and HOSTARCH to build.vars

---

makelib/golang.mk

This reverts commit a45f23747b04ae1bdb2ad3edf1dfbfffbd1e5cbd.
golangci-lint 1.17.1 increased the memory footprint of the CI/CD
processes substantially.
This PR is an alternative to:
* Increasing the RAM on the Jenkins Worker Node
* Decreasing the parallelism, increasing the GC rate, increasing the
lint timeout as is handled by upbound/build#68
Closes #68 
Signed-off-by: Marques Johansson <marques@upbound.io>

Revert "update golangci-lint to 1.17.1"

---

makelib/golang.mk

generate target uses goimports but does not install it if it does not exist, this fixes that
Signed-off-by: Muvaffak Onus <onus.muvaffak@gmail.com>

Install goimports before go generate

---

makelib/golang.mk

Removes error that requires for `GO_STATIC_PACKAGES` to be set to access any go the `golang.mk` targets.

remove error checking if GO_STATIC_PACKAGES defined

---

makelib/golang.mk
makelib/kubebuilder.mk

Signed-off-by: soorena776 <javad@upbound.io>

Modify the golang.mk to support go modules

---

makelib/k8s_tools.mk

This PR adds it into k8s_tools.mk which wil be used for adding annotations to autogenerated Crossplane CRDs with make.

add kustomize into makelib/k8s_tools.mk

---

makelib/helm.mk

This PR updates the version of the helm tool to v2.15.1.  We were using a fairly old version of v2.10.0 which has issues with post-install hooks.

helm: update helm version to v2.15.1

---

cross/Dockerfile
makelib/golang.mk
run

I was having odd bugs showing up with trying to use helm v3 as a dependency saying it couldn't be found, like: `go: helm.sh/helm/v3@v3.0.0: unknown revision helm.sh/helm/v3.0.0`
Upgrading to go 1.13.5 seems to have resolved the issue.
Additionally to support go 1.13:
- golangcilint failed and needed an upgrade
- go proxy doesn't work with private repos, so I've added github.com/upound/* to GOPRIVATE.

Update golangcilint to 1.22.2 and go to 1.13.5

---

cross/Dockerfile
makelib/golang.mk
makelib/helm.mk

Addresses:
- Adding the unzip command to make it possible to unzip zipped files in cross image
- Fixes: upbound/hosted-crossplane-squad#127

Add unzip to cross image

---

makelib/golang.mk

We invoke goimports in two places:
1. Automatically on generated files.
2. When running make imports
1 is bad practice; we should not edit generated code, even using tools. 2 is redundant; make lint invokes goimports via golangci-lint.

Remove goimports

---

makelib/golang.mk

Upgrading golangci-lint to fix build in go 1.14
It fixes the lint errors I got while building crossplane/crossplane and crossplane/crossplane-repos with go 1.14.
Signed-off-by: Artur Souza <artursouza.ms@outlook.com>

Upgrading golangci-lint to fix build in go 1.14

---

makelib/helm.mk
makelib/output.mk

WESAAS does not need publishing to an S3_BUCKET, so making it optional in  `output.mk`
Signed-off-by: Javad Taheri <taheri.javad@gmail.com>

Make S3_BUCKET and publishing to it optional

---

makelib/k8s_tools.mk

This updates Kind to use k8s v1.17 and also adds some new features. There are some minor updates that will be required in https://github.com/crossplane/crossplane/blob/master/cluster/local/integration_tests.sh, which I am happy to make :+1: 

Bump KIND version to v0.7.0

---

cross/Dockerfile

This updates the cross container go version to include a
workaround for the linux kernel bug described in this
issue https://github.com/golang/go/issues/37436

Bump cross container Go version to 1.14.4

---

makelib/helm.mk

Every time a minikube or kind is initiated, Helm image is pulled from GCR. If we expose the version, then those scripts could just pull the image once into the local and load it to the node every time from the local machine instead of downloading it every time.
Something like this would be possible in [`kind.sh up`](https://github.com/crossplane/crossplane/blob/master/cluster/local/kind.sh#L45) command:
```
docker pull gcr.io/kubernetes-helm/tiller:${HELM_VERSION}
kind load docker-image gcr.io/kubernetes-helm/tiller:${HELM_VERSION}
```
Tested with above code snippet in `kind.sh`.

Expose Helm version as buildvar

---

makelib/golang.mk

Logs during test cause change in structure of `unit-tests.log` file and some test results might be ignored and not included to `unit-tests.xml`. It is used to checking result of running tests, so even if some tests are failed exit code of `make test` is `0`. Because of that our circleci build missed failed tests too and marked build as passed. 
Adding  `-v` streams logs output as it happens, rather than adds to the end of test run. I've tried to run build with these changes and it fixed circleci build (it failed for failed tests)

Fix test result

---

makelib/golang.mk
makelib/helm.mk

Expected to fix following sporadic build failure for repos with more than one helm charts (e.g. wesaas):
```
20:17:17 [ OK ] helm package maincluster-operator 0.14.0-alpha1.25.gdde3e70
20:17:17 [ .. ] helm package crossplane-cluster-velero 0.14.0-alpha1.25.gdde3e70
Successfully packaged chart and saved it to: /home/upbound/go/src/github.com/upbound/wesaas/_output/charts/hostcluster-base-0.14.0-alpha1.25.gdde3e70.tgz
Successfully packaged chart and saved it to: /home/upbound/go/src/github.com/upbound/wesaas/_output/charts/hostcluster-tiers-gcp-0.14.0-alpha1.25.gdde3e70.tgz
Successfully packaged chart and saved it to: /home/upbound/go/src/github.com/upbound/wesaas/_output/charts/hostcluster-tiers-localdev-0.14.0-alpha1.25.gdde3e70.tgz
WARNING: Deprecated index file format. Try 'helm repo …
```

Helm: fix race condition for parallel package's

---

README.md
makelib/helm.mk
makelib/k8s_tools.mk
makelib/local.mk
scripts/load-configs.sh
scripts/localdev-deploy-component.sh
scripts/localdev-prepare.sh
scripts/localdev-remove-component.sh
scripts/localdev-scaffold.sh
scripts/utils.sh

Introducing local development targets:
New build commands and related config:
- `kind.up`: stands up a kind cluster and add context to the kubeconfig
- `KIND_CLUSTER_NAME ?= local-dev`
- `KIND_CONFIG_FILE` - Ability to set different version or any config for kind
- `KUBECONFIG ?= $(HOME)/.kube/config`
- `kind.down`: deletes kind cluster
- `kind.setcontext`: sets kubeconfig context to use config of the kind cluster.
- `local.helminit`: initializes helm2 with pre-pulled/loaded tiller image and proper cluster roles, updates helm repos.
- `local.up`: `kind.up` + `local.helminit`
- `local.down`: `kind.down` + any necessary cleanup
- `local.deploy.%`: installs/upgrades a local/external component (e.g. helm chart)
- `local.remove.%`: removes component
- `local.scaffold`: scaffold initial local …

Add Local Development Targets

---

makelib/local.mk

`make clean` already delete whole `.work` directory. Trying to delete `.work/local` with `make clean` causes sporadic errors.

Don't clean local with local down

---

makelib/local.mk

- kind.up needs to run first so that the kind kubeconfig context exists

Adding kind.up prereq to kind.setcontext target

---

makelib/golang.mk

I'd like to update our linting Github action(s), and the actions don't support this fairly old version of golangci-lint. I've tested the new version against crossplane, crossplane-runtime, and provider-gcp. It introduces some new lint rules that will need to be addressed, but otherwise works fine.

Bump golangci-lint version

---

README.md

With #106 helm target moved to a separate .mk file, for re-usability, breaking current setup in Readme which is fixed with this commit.

Update readme: include k8s_tools for helm

---

makelib/local.mk

HELM_HOME is defined in `makelib/helm.mk`, however, it is not possible to include `makelib/helm.mk` if repo has no helm charts where it fails with `the variable HELM_CHARTS must be set prior to including helm.mk`.
We want to still use local dev tooling even the repo has no helm charts (e.g. deploying existing charts from other repositories).

Fix undefined HELM_HOME if makelib/helm not included

---

makelib/helm.mk
makelib/local.mk
scripts/load-configs.sh
scripts/localdev-deploy-component.sh

- helm3 no longer uses HELM_HOME env var: https://helm.sh/docs/faq/#xdg-base-directory-support (causing users directories to be used otherwise)
- we don't need helm init for localdev in case of helm3

Fixes for helm3

---

makelib/golang.mk

Signed-off-by: 天元 <jianbo.sjb@alibaba-inc.com>
`go test -race` need CGO_ENABLED=1.
Tested with my personal repo: https://github.com/wonderflow/test-build
1. add build as submodule with this updated PR
2. run make test

make go covermod configurable

---

makelib/k8s_tools.mk

Due to the announcement form Helm https://helm.sh/blog/new-location-stable-incubator-charts/,
the new location for helm chart repository has been upgraded to Github Pages. We MUST update the
repositories we use before November 13, 2020. Helm v2.17.0 and v3.4.0 have been released to
help use the new location.
Signed-off-by: zzxwill <zzxwill@gmail.com>

Make helm3 version configurable

---

cross/Dockerfile

- Uses current method to install `awscli`: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
- Pins `awscli` version to `2.1.21` to help with reproducible builds.

Update awscli install method

---

cross/Dockerfile
makelib/golang.mk

Closes https://github.com/upbound/build/pull/122
Per https://github.com/upbound/build/pull/122#discussion_r508284675, most (all?) of our projects now use Go modules, which allow a module to declare the version of Go it targets.
It could be that the purpose of this variable is to gate the versions of Go that `upbound/build` as a library of Makefiles supports, rather than the versions of Go that _code built with_ `upbound/build` supports. If this is the case, I'd argue that during the the two years I've been using this library we've yet to encounter a new version of Go that has required anything other than a bump to this whitelist and that we never test that the older versions of Go still work. I suspect it would be more productive to pay the price of a newer version of Go breaking the …

Build with Go 1.16.1, and remove the whitelist of supported versions

---

makelib/helm.mk
makelib/k8s_tools.mk
scripts/localdev-deploy-component.sh

This PR adds an option to disable strict helm linting which fails the build with warnings. Ideally, we should fix warnings instead of disabling strict linting, however, sometimes this is not possible (or does not make sense) like an incorrect warning on the helm side. 
Currently, [this issue](https://github.com/helm/helm/issues/9197) on helm side prevents use prevents us using helm 3 with Crossplane chart. With this option, we will be able to (temporarily) disable strict linting.
This PR also updates helm version to latest (v3.5.3) which includes PRs fixing[ categorization of linting issues ](https://github.com/helm/helm/issues/8596)as warnings instead of errors.

Option to disable helm strict linting

---

makelib/image.mk

Allows for publishing images from branches named main.

Support publishing images from main

---

makelib/golang.mk

This currently results in make spitting out a fairly opaque EOF error from bash:
```console
$ make
01:08:51 [ .. ] verify dependencies have expected content
all modules verified
01:08:51 [ OK ] go modules dependencies verified
01:08:51 [ .. ] golangci-lint
01:08:51 [ OK ] golangci-lint
01:08:52 [ .. ] go build linux_amd64
/bin/bash: -c: line 1: syntax error: unexpected end of file
make[3]: *** [build/makelib/golang.mk:153: go.build] Error 1
make[2]: *** [build/makelib/common.mk:292: do.build.platform.linux_amd64] Error 2
make[1]: *** [build/makelib/common.mk:305: build.all] Error 2
make: *** [build/makelib/common.mk:313: build] Error 2
```
I've verified that with this change things proceed as expected!

Fix syntax error when building Go test packages

---

makelib/image.mk

This is required, otherwise artifacts cannot be published https://github.com/crossplane/provider-aws/runs/2488167717?check_suite_focus=true

image.mk: replace the last remainingn HOSTARCH usage with SAFEHOSTARCH

---

makelib/common.mk

Adds main as a list of suitable channels for publishing output
artifacts.
Fixes #147 
(some context: https://github.com/upbound/up/blob/8aad71f5f04b7354cd31141ff193528d911c1b44/.github/workflows/ci.yml#L280)

Allow publishing to channel main

---

makelib/helm.mk

Fixes the following errors related to the updated charts repo:
1. error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository
2. cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden

Fix helm init issue related to stable repo

---

makelib/common.mk

When the tag contains two hyphens, we end up generating versions not sortable as semver. See https://github.com/upbound/universal-crossplane/issues/109 for more details.
This PR fixes that by converting `-` to `.` in that case just like we do other hyphens in `git describe` output.

Fix version for two hypens in tag

---

makelib/common.mk
makelib/golang.mk
makelib/local.mk

We've been using this target in Crossplane projects for some time. The idea is that's it's a one-shot folks can run to validate that their branch is not likely to fail CI when they open a branch, by ensuring codegen has run, and that any linters and tests pass.
I have:
I've validated that this works with crossplane/crossplane (with a few tweaks to its own `Makefile`).

Add a common `make reviewable` target

---

makelib/golang.mk

We're integrating ACK into our CI and it depends on having `goimports` available on host. We need this change to be able to install it in `Makefile`.
I have:
Manually.

Add goimports to the list of golang tools

---

cross/Dockerfile
makelib/common.mk
makelib/k8s_tools.mk

Signed-off-by: Taylor Thornton <taylor@upbound.io>
The current build submodule makes an effort to not use darwin_arm64. Unfortunately, being on an Apple M1 MBP, that makes it so certain builds don't quite work.
In addition to the script updates, I upgraded kind as the earlier version defined would result in:
```
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged build-07a4805a-inttests-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 139
Command Output: SIGSEGV: segmentation violation
PC=0x0 m=0 sigcode=0
goroutine 1 [running]:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```
when running `make e2e` on crossplane/crossplane.
I have: …

Adds support for darwin amd64 and arm64

---

makelib/helm.mk

In Helm3, the linting rules have changed slightly. Now if you have a dependency defined in your Chart.yaml, but don't have a corresponding subchart directory, linting will fail. This change adds a step to ensure helm has the full view of the dependencies when it attempts linting.
I have:
Locally on the enterprise-server repo.

Add dep update step so that charts with subcharts don't fail linting

---

makelib/k8s_tools.mk

As part of dropping support for Helm 2, the location for all published
helm versions has been moved to get.helm.sh. The currently used link is
now failing.
See https://github.com/helm/helm/issues/10005 and https://helm.sh/blog/get-helm-sh/
Also see example failure in https://github.com/crossplane/crossplane/pull/2484/checks?check_run_id=3350283419
I have:
This has not been individually tested, but it matches the same steps we currently use for Helm 3 (see a few lines below in same file). We could probably combine these two, but I am keeping them separate for now to preserve the required explicit declaration to use Helm 3.

Update helm 2 download location

---

makelib/docs.mk

Adds a flag to indicate that a certain version of the documentation
should not be published. If DOCS_VERSION_ACTIVE is set to false, the
version will be removed from documentation if it exists. This
effectively allows a given release branch to be retired by adding this
flag and merging the commit.
xref https://github.com/crossplane/crossplane.github.io/issues/107
**How this works**: when a release branch goes out of support, we will add a formalized process that includes opening a PR to the branch adding `DOCS_VERSION_ACTIVE = false` to the `Makefile`. When that PR is merged, it will trigger a docs build and publish, which will remove all of the docs for that branch, then [update the …

Optionally publish a valid docs version

---

makelib/common.mk

Signed-off-by: Christopher Haar <chhaar30@googlemail.com>
show check-diff modified output for specific files
old:
```
10:44:14 [ .. ] checking that branch is clean
10:44:14 [FAIL]
make: *** [check-diff] Error 1
```
new:
```
10:50:25 [ .. ] checking that branch is clean
M build
M package/crds/xxx.aws.crossplane.io_xyz.yaml
M package/crds/xxx.aws.crossplane.io_abc.yaml
10:50:25 [FAIL]
```
I have:
via crossplane/provider-aws

feat(check-diff): generate check-diff output

---

makelib/golang.mk

In https://github.com/crossplane-contrib/provider-tf-azure/pull/1, for a generated file we get the following golangci-lint error:
```
internal/controller/zz_setup.go:295:98: `hdinsight` is a misspelling of `hindsight` (misspell)
hdinsightmlservicescluster "github.com/crossplane-contrib/provider-tf-azure/internal/controller/hdinsight/hdinsightmlservicescluster"
```
This PR suggests a change that will allow us to pass extra command-line options to `golangci-lint` from a repo's Makefile. The intended use case is to pass extra command-line options from a repo's Makefile.
I have:
I have tested this PR against https://github.com/crossplane-contrib/provider-tf-azure/pull/1 with and without `GO_LINT_ARGS` Makefile variable being defined.

Add GO_LINT_ARGS make variable to pass extra command-line options to golangci-lint

---

makelib/image.mk
makelib/imagelight.mk

Adds a new image building orchestration Makefile that is mutually
exclusive with image.mk. The purpose of imagelight.mk is to defer more
of the functionality to the individual image makefiles that exist in a
repo that consumes the build submodule. This use case has become more
desirable as we move towards tools such as buildx, but imagelight does
not specifically constrain the consumer to any one image building tool.
There are a few notable differences from image.mk, including but not
limited to:
- We do not save images as tarballs to an output directory, though
individual image makefiles in a repo could opt to do so on their own.
- We support publishing to multiple registries and repositories. An
arbitrary number of REGISTRY_ORGS can be defined in the top-level
Makefile in a repo, and …

Add imagelight as alternative image building orchestrator

---

makelib/imagelight.mk

Removes the non-existent img.cache target as a prereq to build.done.
I have:
Tested with https://github.com/crossplane/crossplane/pull/2718 (which is currently failing because of this).

Remove img.cache as build.done prereq

---

makelib/k8s_tools.mk

Adds machinery to download and install up in the tools directory.
I have:
Tested with `provider-aws` using the following path on the integration tests:
```
diff --git a/cluster/local/integration_tests.sh b/cluster/local/integration_tests.sh
index 6077c5bd..04b12748 100755
--- a/cluster/local/integration_tests.sh
+++ b/cluster/local/integration_tests.sh
@@ -42,6 +42,7 @@ eval $(make --no-print-directory -C ${projectdir} build.vars)
SAFEHOSTARCH="${SAFEHOSTARCH:-amd64}"
BUILD_IMAGE="${BUILD_REGISTRY}/${PROJECT_NAME}-${SAFEHOSTARCH}"
+PACKAGE_IMAGE="crossplane.io/inttests/${PROJECT_NAME}:${VERSION}"
CONTROLLER_IMAGE="${BUILD_REGISTRY}/${PROJECT_NAME}-controller-${SAFEHOSTARCH}"
version_tag="$(cat ${projectdir}/_output/version)"
@@ -68,7 …
```

Add `up` download machinery

---

makelib/imagelight.mk

When using a Darwin OS and imagelight.mk, `img.build` targets are being fed `IMAGE_PLATFORMS=darwin_${HOSTARCH}`. However, this is generally invalid for the images that are published/consumed by upbound and crossplane. This change substitutes `linux` for `darwin` in the event this is seen while attempting to build the images.
I have:
Tested this behavior on a consuming repo. With this change, attempts to build an image have the appropriate `IMAGE_PLATFORMS` being fed to the docker command.
Before:
```bash
14:57:09 [ .. ] docker build build-1e336c54/shimmer-sql-arm64
docker buildx build --load \
--platform darwin/arm64 \
-t build-1e336c54/shimmer-sql-arm64 \
/var/folders/qh/kb2fj2915zn36r801mw29q_00000gn/T/tmp.3okr3pfr || (echo `date +%H:%M:%S` [FAIL] && false)
```
After:
```bash
docker …
```

Replace darwin with linux when building images using buildx

---

makelib/golang.mk

`go.lint` takes quite a while for big repositories like provider-aws but it's actually not relevant for building. The check is done by other mechanisms like `make reviewable` when necessary. This PR removes the `go.lint` from the `build` target.
I have:
Manually with provider-aws

go: do not run go.lint for every build

---

makelib/k8s_tools.mk

The curl command installing kubectl simply outputs to a directory that it expects to already exist. If, however, you are starting from scratch, outputting the relevant binary results in an error. Debugging points to the lack of the target directory causing the issue.
I have:
Prior to these changes, running a target like so:
```Makefile
install-xp: $(KUBECTL) $(HELM)
```
Results in:
```bash
$ make install-xp
18:54:34 [ .. ] installing kubectl v1.23.5
curl: (23) Failed writing body (0 != 1388)
18:54:34 [FAIL]
```
After adding these changes:
```bash
$ make install-xp
18:51:08 [ .. ] installing kubectl v1.23.5
18:51:10 [ OK ] installing kubectl v1.23.5
18:51:10 [ .. ] installing helm3 v3.7.1
18:51:10 [ OK ] installing helm3 v3.7.1
```

Add `--create-dirs` flag for curl commands outputting to subdir

---

makelib/local.mk
scripts/localdev-scaffold.sh

Minor change to have `local.mk` work with `imagelight.mk`
I have:
```
REGISTRY_ORGS ?= docker.io/upbound
IMAGES = some-image
-include build/makelib/imagelight.mk
-include build/makelib/local.mk
```
make build local-dev

Local dev update to work with imagelight.mk

---

makelib/k8s_tools.mk

Updates k8s_tools to allow for the release channel to be specified when
installing up.
I have:
Verified that setting `UP_CHANNEL=main` and `VERSION=v0.12.0-rc.0.30.g591e132` leads to successful install.

Allow specifying release channel for up install

---

makelib/common.mk

Needed in mono repos where there might be tags that are put in place by other projects in the same repo. This allows each project to specify a glob to match.
I have:
Projects could opt in to use the new `PROJECT_VERSION_TAG_GROUP`. The following are the scenarios I tried to make sure the ones that do not opt it are not affected and the ones that do get the expected behavior, that is tagging with `prefix/v0.0.0` and release branch named `release-prefix-0.1`.
I commented out all `git` commands under `releases.tag` target to make sure it doesn't affect the real repos but still print the command and added a target `make vers` temporarily to see what's calculated as `VERSION`:
```
vers:
@(INFO) version is $(VERSION)
```
I tried the same scenarios in `crossplane/crossplane` as well to make sure …

common: add ability to provide glob to match tags during version

---

makelib/common.mk

Fixes #178.
Added check to translate aarch64 to arm64 in `makelib/common.mk`.

Translate aarch64 to arm64

---

makelib/common.mk

In some rare cases (e.g. on NixOS) bash is not at /bin/bash. Using env to find where the shell actually is is a fairly common pattern per https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability. It's also possible that /usr/bin/env is not at that path, but anecodally the internet considers it to be "more likely" to be there than /bin/bash, which is not the standard path on most BSDs and some rare Linux variants.
I have:
I've made the edit locally and run `make reviewable` against https://github.com/crossplane/crossplane.

Use /usr/bin/env to find bash

---

makelib/image.mk
makelib/imagelight.mk

This adds a fallback to `sha256sum` if `shasum` is not available.
Fixes #191 
I have:
Manually on Fedora 36.

fix: Fallback to sha256sum if shasum is not available

---

makelib/common.mk
makelib/k8s_tools.mk

Stop hardcoding `SAFEHOSTARCH` to `amd64` on darwin.
Running make on `github.com/upbound/xgql` with these changes fetches the correct helm binaries:
```
lipo -detailed_info /Users/adi/src/github.com/upbound/xgql/.cache/tools/darwin_arm64/helm-v3.7.1
input file /Users/adi/src/github.com/upbound/xgql/.cache/tools/darwin_arm64/helm-v3.7.1 is not a fat file
Non-fat file: /Users/adi/src/github.com/upbound/xgql/.cache/tools/darwin_arm64/helm-v3.7.1 is architecture: arm64
```
I have:

Stop hardcoding `SAFEHOSTARCH` to `amd64` on darwin

---

makelib/golang.mk

Update `golangci-lint` to `1.47.1` to be able to install `darwin_arm64` binaries
```
✨  Done in 0.31s.
10:05:52 [ .. ] verify dependencies have expected content
all modules verified
10:05:54 [ OK ] go modules dependencies verified
10:05:54 [ .. ] installing golangci-lint-v1.31.0 darwin-arm64
curl: (22) The requested URL returned error: 404
mv: rename /Users/adi/src/github.com/upbound/xgql/.cache/tools/darwin_arm64/tmp-golangci-lint/golangci-lint to /Users/adi/src/github.com/upbound/xgql/.cache/tools/darwin_arm64/golangci-lint-v1.31.0: No such file or directory
10:05:54 [FAIL]
make[1]: *** [/Users/adi/src/github.com/upbound/xgql/.cache/tools/darwin_arm64/golangci-lint-v1.31.0] Error 1
make: *** [lint] Error 2
```
```
✨  Done in 0.31s.
10:23:08 [ …
```

Update `golangci-lint` to `1.47.1`

---

cross/Dockerfile
makelib/golang.mk

- Enforce/Require usage of Go 1.18
- Drops usage of `-i` flag for go invocations	  
The -i flag installs the packages that are dependencies of the target.
The -i flag is deprecated. Compiled packages are cached automatically.
I have:

Go: Clamp down minimum required version to 1.18

---

makelib/golang.mk
makelib/local.mk
run

Cleans up some of the stuff in the Go build module that is no longer relevant. Inline comments follow
I have:
Tested all `go` targets with `managed-control-plane` and `shimmer`

Go: miscellaneous cleanup

---

scripts/localdev-prepare.sh

Fixes the following error when running `make local.deploy.<component-name>` which has been occurring since bumping the kustomize version in https://github.com/upbound/build/commit/3f7115eb19d289b0906498bfe51a8801f8107cc0
```
Error: error parsing regexp: missing argument to repetition operator: `*`
```
I have:

Fix kustomize patch target regex

---

makelib/local.mk

This PR removes installing istio client and helm v2 with local dev setup.
I have:
By running local dev in a depending repo.

Istio and helm v2 should not be a requirement for local dev

---

makelib/golang.mk

Fixes `bash: go.mod: command not found`
I have:
- Checkout this branch
- Run `make go.modules.tidy.check` with a dirty go.mod/go.sum 
- Should output `go.mod is not tidy` instead of `bash: go.mod: command not found`

go.modules.tidy.check: fix `bash: go.mod: command not found`

---

makelib/xpkg.mk

To make recently introduced xpkg build functionality work with configuration packages as well, we will be passing `--controller` argument to xpkg build command only for provider packages.
I have:
Together with [platform-ref-gcp](https://github.com/upbound/platform-ref-gcp) with `make build` using the following Makefile:
```
PROJECT_NAME := platform-ref-gcp
PROJECT_REPO := github.com/upbound/$(PROJECT_NAME)
PLATFORMS ?= linux_amd64 linux_arm64
include build/makelib/common.mk
UP_VERSION = v0.13.0
UP_CHANNEL = stable
-include build/makelib/k8s_tools.mk
XPKG_REG_ORGS ?= xpkg.upbound.io/upbound
XPKG_REG_ORGS_NO_PROMOTE ?= xpkg.upbound.io/upbound
XPKGS = $(PROJECT_NAME)
-include build/makelib/xpkg.mk
build.init: $(UP)
```

Pass controller flag only for provider packages

---

makelib/helm.mk

This removes exports of the `XDG_*` environment variables and exports `HELM_*_HOME` instead which has the same effect in Helm but avoids the side effects with Go that causes `GOCACHE` to be set to `.work/go-build`.
I have:
Manually

fix:(helm): Set HELM_*_HOME env vars to avoid side effects with go

---

makelib/common.mk

In my local with make 3.8, `IMAGE_PLATFORMS` is calculated as `linux/amd64,linux/arm64` but in Ubuntu 22.04, make version is 4.3 and it calculates it as `linux/amd64 linux/arm64,` which breaks `imagelight.mk`. I've seen this [in CI ](https://github.com/upbound/provider-aws/actions/runs/3205351360/jobs/5237762811)and I was able to reproduce it in a Ubuntu 22.04 docker container.
What's going on is that apparently, `SPACE` definition we had is not compatible with the newer version and others have also struggled to define space character in Make. After digging, I found this trick (discussed [here](https://groups.google.com/g/gnu.utils.help/c/Kph-2Mk4NxU/m/QQMgBYynsuAJ)) which looks pretty explicit and proved to to work.
I have:
Manually with both make 4.3 (GNU) and 3.8 (Apple) by running …

common: adopt make 4 changes around how to define space

---

makelib/common.mk

As described in https://github.com/upbound/build/issues/211 , the current calculations of these variables are wrong if the version has more than 2 `.` characters.
Fixes https://github.com/upbound/build/issues/211
I have:
Dirty version:
```bash
export VERSION="v0.17.0-3.gb4eee9f.dirty"
export VERSION_MAJOR=$(echo "${VERSION}" | cut -d'.' -f1 | sed '1s/^.//')
export VERSION_MINOR=$(echo "${VERSION}" | cut -d'.' -f2)
export VERSION_PATCH=$(echo "${VERSION}" | cut -d'.' -f3-)
```
```bash
echo ${VERSION_MAJOR} # 0
echo ${VERSION_MINOR} # 17
echo ${VERSION_PATCH} # 0-3.gb4eee9f.dirty
```
Normal tag version:
```bash
export VERSION="v0.17.1"
export VERSION_MAJOR=$(echo "${VERSION}" | cut -d'.' -f1 | sed '1s/^.//')
export VERSION_MINOR=$(echo "${VERSION}" | cut -d'.' -f2)
export …
```

common: calculate major, minor and patch versions correctly

---

makelib/docs.mk

Adds support for overriding the version of the documentation being
produced, which can be useful for local development.
Separates docs generation and publishing, and adds a run target that
just calls make again on the docs repo run target.
I have:
Verified ability to run locally with https://github.com/crossplane/crossplane.github.io/pull/166 and https://github.com/crossplane/crossplane/pull/3373

Enhance docs local development capabilities

---

makelib/k8s_tools.mk

This PR is adding uptest as a tool.
I have:
With the following target:
```makefile
testing-uptest: $(UPTEST)
$(UPTEST) --help
```

Add uptest tool

---

makelib/controlplane.mk
makelib/k8s_tools.mk
makelib/local.xpkg.mk

Adds targets to deploy a locally build configuration package.
It also adds targets to start and stop a control plane (a.k.a. K8s + XP)
I have:
With this PR: https://github.com/upbound/platform-ref-gcp/pull/25
See `uptest` target.

Add targets to deploy a locally build configuration package

---

makelib/controlplane.mk

Adds `controlplane.dump` target to dump cluster information for debugging/troubleshooting.
I have:
Together with https://github.com/upbound/platform-ref-azure/pull/20

Add control plane dump target

---

makelib/controlplane.mk

Extends `controlplane.dump` target further with Crossplane resources as suggested by @muvaf [here](https://github.com/upbound/build/pull/215#issuecomment-1284458650).
I have:
Tested each command individually.

Dump Crossplane resources as well

---

makelib/controlplane.mk
makelib/local.xpkg.mk

This PR aims to simplify provider deployment currently achieved by scripts like [this](https://github.com/upbound/provider-aws/blob/main/cluster/install_provider.sh) by extending recently added local.xpkg.deploy target with Provider support.
I have:
Tested with [provider-civo](https://github.com/crossplane-contrib/provider-civo) by adding the following lines to Makefile:
```Make
CROSSPLANE_NAMESPACE = upbound-system
-include build/makelib/local.xpkg.mk
-include build/makelib/controlplane.mk
```
Then run
```
make controlplane.up build local.xpkg.deploy.provider.provider-civo
```
Check the status of the provider:
```shell
kubectl get provider.pkg
NAME            INSTALLED   HEALTHY   PACKAGE                       AGE
provider-civo   True        True      provider-civo-v0.1-dirty.gz   68s …
```

Add support for Provider in local.xpkg.deploy

---

makelib/golang.mk

Signed-off-by: Chuan-Yen Chiang <cychiang0823@gmail.com>
In this PR, I bump up the `golangcilint` version from `1.47.1` to `1.49.0` to support build with go version higher than 1.17.
It would be really helpful to merge this change because all `crossplane` related projects are using the same build project, like `provider-template`, `crossplane` and `crossplane-runtime`. 
I have:
I tested this change in `provider-template` project with the following go version: 
* `1.17`
* `1.18`
* `1.19`
All above go versions are able to pass the `make reviewable` command. Before that, the command only compatible with `1.17` and show the following message when using `1.18` and `1.19`
```
...
failed to load package goarch: could not load export data: cannot import "internal/goarch"
```

Bump up GOLANGCILINT_VERSION to support build with go 1.19

---

makelib/golang.mk

It's been getting in the way unexpected places as discussed [here](https://github.com/upbound/build/pull/200) and [here](https://github.com/upbound/build/pull/195). And it'd been removed once in the past [here](https://github.com/upbound/build/pull/140). Recently, it blocked the UXP release because [promote job](https://github.com/upbound/universal-crossplane/actions/runs/3401410191/jobs/5656492204) didn't have a correct Go version, which is unrelated to what it does - it probably shouldn't include `golang.mk` anyway, but the way Makefiles are structured, everything is included during invocation of any target.
I have:
Ran `make reviewable` on UXP repo after downgrading to 1.18 and it worked as expected when I ran `make reviewable` with go 1.19.

golang: remove go version check

---

makelib/k8s_tools.mk

Otherwise, `make uptest` would fail with the following in a clean clone:
```bash
❯ UPTEST_EXAMPLE_LIST=examples/iam/policy.yaml make uptest
10:07:13 [ .. ] installing uptest /Users/hasanturken/Workspace/upbound/provider-aws/.cache/tools/darwin_arm64/uptest-v0.3.0
curl: (23) Failure writing output to destination
10:07:14 [FAIL]
```
I have:
With provider-aws; 
```bash
❯ rm -rf .cache
❯ UPTEST_EXAMPLE_LIST=examples/iam/policy.yaml make uptest
10:07:37 [ .. ] installing kubectl v1.24.3
10:07:43 [ OK ] installing kubectl v1.24.3
...
```

Create tools dir if not exist with Uptest target

---

makelib/docs.mk

Updates docs machinery to be able to symlink when running locally but copy fully when generating for publish.
I have:
Ran in crossplane/crossplane and verified that `make docs.run` and `make publish` worked correctly.

Separate docs generation from running locally

---

makelib/common.mk

This PR added an error message for failing check diff.
I have:
Manually tested with provider-gcp

Add check diff error message

---

makelib/golang.mk

Fixes https://github.com/golangci/golangci-lint/issues/3565

Bump version of golangci-lint to v1.51.0

---

makelib/helm.mk

Adds helm chart's README generation using github.com/norwoodj/helm-docs/cmd/helm-docs.
This should be explicitly enabled by the callers by setting `HELM_DOCS_ENABLED = true`, this way we won't overwrite existing READMEs.
I have:
`make HELM_DOCS_ENABLED=true helm.generate` properly generates the crossplane helm chart README in https://github.com/crossplane/crossplane/pull/3978 if the proper template is specified as in the PR description.
It's also properly run when running `make check-diff`.

feat: generate helm chart README with helm-docs

---

makelib/controlplane.mk
makelib/local.xpkg.mk

This PR makes the Crossplane namespace configurable for `controlplane.up` command.
I have:
Together with https://github.com/crossplane-contrib/provider-kubernetes/pull/120
```
make e2e
```

Make Crossplane namespace configurable for controlplane.up

---

makelib/golang.mk

The recent versions contain a couple of updates in regards to memory management
Raise `golangci-lint` version, latest version contains some improvements in regards of memory usage.
I have:

chore: raise `golangci-lint` version

---

makelib/controlplane.mk

add option to specify crossplane args for alpha flags
Fixes #
I have:
specify in makefile no `CROSSPLANE_ARGS`
```
[...]
Containers:
universal-crossplane:
Image:      upbound/crossplane:v1.12.2-up.2
Port:       9443/TCP
Host Port:  0/TCP
Args:
core
start
[...]
```
specify in makefile `CROSSPLANE_ARGS = "--enable-environment-configs"`
```
[...]
universal-crossplane:
Image:      upbound/crossplane:v1.12.2-up.2
Port:       9443/TCP
Host Port:  0/TCP
Args:
core
start
--enable-environment-configs
[...]
```
speficy in makefile `CROSSPLANE_ARGS = "--enable-environment-configs,--enable-composition-functions"`
```
[...]
universal-crossplane:
Image:      upbound/crossplane:v1.12.2-up.2
Port:       9443/TCP
Host Port:  0/TCP
Args:
core
start
--enable-environment-configs …
```

feat(uxp): add option to specify crossplane args

---

makelib/local.xpkg.mk

In the context of official provider testing, we would like to be able to run [uptest](https://github.com/upbound/uptest) using the family providers instead of the monolithic providers to avoid the CRD scaling issues we've been observing with them. Each resource provider in a provider family declares a package dependency to the family's config provider and the Crossplane RBAC manager is responsible for assigning the required RBAC rules on the config provider resources for the ClusterRole assigned to the family resource provider's K8s ServiceAccount. However, the RBAC manager [refuses](https://github.com/crossplane/crossplane/blob/ce52e336cef34e3879eabbc35b5cc5a04ede24e2/internal/controller/rbac/provider/roles/reconciler.go#L295) to do so if the reg/org of the resource provider's package …

Support skipping dependency resolution of installed Crossplane packages in target local.xpkg.init

---

makelib/k8s_tools.mk

Consume new `up` CLI version required for build after package meta API version was bumped (e.g. upbound/provider-aws#882).
I have:
update Makefile locally:
```
-UP_VERSION = v0.17.0
+UP_VERSION = v0.19.2
```
build:
```
make SUBPACKAGES="config" VERSION=v0.38.0 build.all 
[...]
```
push to registry:
```
make SUBPACKAGES="config" VERSION=v0.38.0 BRANCH_NAME=main publish
15:57:28 [ .. ] Batch processing smaller provider packages for: config
Pushing xpkg to xpkg.staging-eikeagoo.upbound.services/upbound/provider-family-azure:v0.38.0.
xpkg pushed to xpkg.staging-eikeagoo.upbound.services/upbound/provider-family-azure:v0.38.0
15:57:44 [ OK ] Done processing smaller provider packages for: config
```
extract and check CRD:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition …
```

Bump UP_VERSION

---

makelib/output.mk

In Crossplane, we would like to ship pre-releases to get some early eyes on the release. 
However, we don't want this release to be set as the "current" version, which is used by some [installation](https://github.com/crossplane/crossplane/blob/ee4cff4f70505083bf3f054e32ec938ecb373d01/install.sh#L6) scripts to identify the latest stable version.
See the relevant discussion [here](https://github.com/crossplane/crossplane/pull/4871#discussion_r1371900396).
I have:
I'll test this in CI since it requires cloud credentials and is a straightforward minimal change.

Promote: do not set as "current" if it is a pre release

---

makelib/controlplane.mk

I've added two new variables for makefile configuration for setting up UXP with a specific version and enabling the installation of release candidates:
```make
UXP_INSTALL_OPTS = "--unstable"
UXP_VERSION = 1.14.0-up.1.rc.2"
```
These variables allow you to configure UXP with a specific version and enable the installation of RC candidates with the `--unstable` option.
Fixes #
I have:

feat(uxp): add option to specify uxp-version

---

makelib/k8s_tools.mk

This will enable leveraging functionality like render in the build pipelines.
I have:
```make
xrender: $(CROSSPLANE_CLI)
@$(INFO) rendering composition templates for $(COMPOSITION)
@$(CROSSPLANE_CLI) beta render $(RENDER_DIR)/$(COMPOSITION)/xr.yaml $(CONFIGURATIONS_DIR)/$(COMPOSITION)/composition.yaml $(RENDER_DIR)/functions.yaml -o $(RENDER_DIR)/$(COMPOSITION)/observed.yaml
```

Add Crossplane CLI as a tool

---

makelib/k8s_tools.mk

We are planning to use `kustomize` to process the family provider CRDs. `kustomize` outputs a multi-document YAML that contains all the processed CRDs and the `up xpkg batch` command relies on the controller-tools naming conventions for the CRD files to decide which CRD goes into which family provider package. Thus it cannot currently partition CRDs if they are in a single file. I checked the possibility of a content based filter (instead of relying on the generated file name) but the  interface is [`io.ReadCloser`](https://pkg.go.dev/io#ReadCloser), which processes a byte stream and is not aware of the YAML documents. Implementing a content filter will introduce unnecessary complexity due to the mismatching abstraction layers. Also considered a filtering …

Add yq As a Tool

---

makelib/controlplane.mk

Frequently when developing providers, I reuse the kind cluster. Occasionally, I've switched kubectl contexts since the last time I ran `make e2e`, and then the build module tries to install crossplane on whatever other kubernetes context I've switched to. 
I have:
I've been using this locally for my tests in both provider-upjet-aws and provider-upjet-kafka.

Always use the kind kubectl context, even if the cluster exists

---

makelib/local.xpkg.mk

Update `local.xpkg.deploy.provider.%` target to use DeploymentRuntimeConfig instead of ControllerConfig. 
This target is used by uptest based e2e testing setup for providers.
I have:
Tested with provider-kubernetes, it is coming up as expected with `make e2e`

Use deploymentRuntimeConfig for local xpkg deploy
