makelib/golang.mk
Coveralls was taking forever to process coverage data, so we're going to try codecov
=> Remove coveralls -> add codecov

makelib/golang.mk
Using cobertura jenkins plugin gives us two advantages on the CICD side:
- Visualize coverage at the build level 
- Enforce coverage threshold (if/when we need it).
=> Add Cobertura code coverage report in text and xml formats, so this can be consumed by CICD tools for coverage display and/or validation/enforcement.

makelib/golang.mk
`goimports` is a superset of `gofmt`. It does everything `gofmt` does, and will also automatically import unambiguous import names referenced within a file, and sort imports.
CC @jbw976 regarding your comment on https://github.com/crossplaneio/crossplane/pull/328. I had thought `make fmt` actually formatted our code, but it appears it operates in more of a linter fashion informing us of poorly formatted code. Either way if we expect folks to run `goimports` rather than `gofmt` it makes sense to switch this out.
Signed-off-by: Nic Cope <negz@rk0n.org>
=> Have make fmt run goimports rather than go fmt

makelib/golang.mk
https://github.com/golang/dep/blob/master/CHANGELOG.md#v051
Signed-off-by: Nic Cope <negz@rk0n.org>
=> Use dep 0.5.1

makelib/golang.mk
- go.imports.fix target to run goimports and update/fix all issues
with import lines
- automatically call new go.imports.fix target after running
go.generate to fix any issues with generated code
=> go: support for goimports

makelib/golang.mk
The `generate` build tag is needed when using Go modules because the tool dependencies must be actual imports, so we want to make sure the file that imports the tools is not built under normal circumstances.
https://github.com/go-modules-by-example/index/blob/master/010_tools/README.md
=> Assume go generate tools are pinned using Go modules (or dep)

makelib/helm.mk
added chart museum via basic http auth as per https://app.zenhub.com/workspaces/cloud-platform-and-infrastructure-5c61e874f2a1351031f66999/issues/upbound/infrastructure-squad/50
=> added chart museum via basic auth

makelib/common.mk
=> Fix 0.0.0 veresions to avoid invalid SemVer 2.0

cross/Dockerfile, makelib/golang.mk
Signed-off-by: Artur Souza <artursouza.ms@outlook.com>
=> Allows build with Go 1.14

makelib/local.mk, scripts/localdev-deploy-component.sh, scripts/localdev-prepare.sh, scripts/utils.sh
=> Local dev improvements for getting shared config

makelib/helm.mk, makelib/k8s_tools.mk, makelib/local.mk, scripts/load-configs.sh, scripts/localdev-deploy-component.sh, scripts/localdev-remove-component.sh
=> Optional helm3 target for local dev

makelib/local.mk
=> Make clean should not wipe local dev env

makelib/local.mk, scripts/localdev-deploy-component.sh, scripts/localdev-prepare.sh, scripts/localdev-remove-component.sh, scripts/utils.sh
- istio support for local dev
- logging improvements with bold style echo_info
=> Local dev: add script only component support

scripts/localdev-deploy-component.sh
Fixes the following error with make local.deploy.<component>:
"Error: unknown shorthand flag: 'l' in -l"
=> Local dev: fix search repo with helm3

makelib/helm.mk, makelib/k8s_tools.mk
- Also bumping to latest istio 1.7.0 -> 1.7.2
=> Conditionally enable Helm3 for building helm artifacts

makelib/local.mk
Planning a better fix with helm2 cleanup.
=> Local dev: fix helm home if helm.mk not included

makelib/local.mk, scripts/localdev-deploy-component.sh, scripts/localdev-prepare.sh
=> Local dev: patch random annotation to restart locally built pods even version not changed

scripts/localdev-deploy-component.sh
=> Local dev: Fix unbound variable if required images not set

scripts/localdev-remove-component.sh
=> Pass release namespace to local-dev helm delete call

makelib/image.mk
https://alpinelinux.org/releases/ - supported until 2022-11-01
=> alpine to 3.13

makelib/k8s_tools.mk
=> Add olm-bundle to k8s tools for generating OLM bundles

makelib/common.mk, makelib/image.mk
Crossplane build and tests have been validated on ppc64le with these changes.
=> Add support for ppc64le

makelib/common.mk
Signed-off-by: Christopher Haar <chhaar30@googlemail.com>
@hasheddan  missed few stuff in my branch we merged with #167 - one commit was missing  - now the feature is working - sorry for that
```
13:43:20 [ .. ] checking that branch is clean
13:43:20 [ OK ] branch is clean
```
```
13:47:06 [ .. ] checking that branch is clean
M Makefile
13:47:06 [FAIL]
make: *** [check-diff] Error 1
```
Fixes #
I have:
crossplane/provider-aws
=> feat(check-diff): generate check-diff output

.gitignore, cross/Dockerfile
Updates Go to 1.17.5
I have:
N/A
=> Update go to 1.17

makelib/image.mk
This PR bumps the manifest-tool version to v1.0.3
Fixes #179 
I have:
I have manually run `make build publish` with the patch on the provider-helm repository.
=> Bump manifest-tool version to v1.0.3

makelib/golang.mk
Changes the error to be more verbose with instructions
I have:
=> Better error message for `go.modules.tidy.check` failures

makelib/k8s_tools.mk, makelib/local.mk
Signed-off-by: Bulat Shakirzyanov <83289+avalanche123@users.noreply.github.com>
Use latest up and export it for consumption from scripts
I have:
```bash
$ make -f makelib/k8s_tools.mk
KIND=/kind-v0.14.0
KUBECTL=/kubectl-v1.24.3
KUSTOMIZE=/kustomize-v4.5.5
OLM_BUNDLE=
UP=/up-v0.12.2
HELM=/helm-v2.17.0
HELM3=/helm-v3.9.1
KUTTL=/kuttl-0.12.1
```
=> update and export up

makelib/xpkg.mk
Adds an xpkg.mk library for building and publishing bundled provider
packages.
I have:
See https://github.com/crossplane-contrib/provider-aws/pull/1460 for extensive testing in a real-world scenario.
=> Add machinery for building and publishing bundled provider packages

makelib/common.mk
Similar to others, it's needed in cases downstream scripts need to use it.
I have:
N/A
=> common: add PLATFORM and VERSION to buildvars

makelib/k8s_tools.mk
k8s_tools: use the latest up cli version
I have:
In crossplane/provider-template locally.
=> k8s_tools: use the latest up cli version

makelib/golang.mk
To include new features and fixes
I have:
Locally
=> go: update golangci-lint to the latest

makelib/golang.mk
Bump to the recent golangci-lint version that contains performance-related fixes
I have:
local `make reviewable` in provider-azure with the newer version
=> Bump golangci-lint to v1.54.0

makelib/k8s_tools.mk
* Main motivation for the bump is the docker compatibility fix released in https://github.com/upbound/up/releases/tag/v0.27.0
Fixes #
I have:
with provider-terraform local build
=> Bump default up version

makelib/k8s_tools.mk
Added kyverno chainsaw installation to k8s_tools.
I have:
- [-] Run `make reviewable` to ensure this PR is ready for review.
- [-] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.
Executed commands and verified download of kyverno chainsaw.
=> add kyverno chainsaw to k8s_tools install

makelib/k8s_tools.mk
Fixes #
- malformed download url
- reference of chainsaw in tools cache
I have:
- [-] Run `make reviewable` to ensure this PR is ready for review.
- [-] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.
Verified download from within Makefile that is using chainsaw.
=> update chainsaw install

README.md
Fixes https://github.com/crossplane/crossplane/issues/1583
I have:
=> Direct Crossplane providers to the crossplane submodule
